{{- if ne .Values.global.env "prod"}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "elastic-sc"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}